### ISSUE TITLE
Can `Context` or `state` be exported?

### ISSUE THREAD

**Issue by i-tengfei** [frontendphil/react-undo-redo#211]
I want to persist the whole `state` and restore it later.

**Comment by frontendphil** [comment]
With the "whole state" do you mean including the `past` and `future` parts? Right now, these are intentionally not exposed as they're an implementation detail. But I guess it might not be too much trouble to give you access to them.

**Comment by frontendphil** [comment]
I've just released 2.1.0 https://github.com/frontendphil/react-undo-redo/releases/tag/v2.1.0 which should solve this.
