### ISSUE TITLE
Don’t add to history if action is a noop?

### ISSUE THREAD

**Issue by mrcoles** [frontendphil/react-undo-redo#332]
Quick feature request and curious of your thoughts—if the reducer returns the same state (via object reference equality) after a dispatch, then it appears that a new state is added to the history. Would it make sense to change it to not add to the history in this scenario? Alternatively, a custom grouping function could control this one way or the other, e.g., https://github.com/frontendphil/react-undo-redo/issues/331

**Comment by frontendphil** [comment]
@mrcoles, great idea! I've added the feature you've described. Since this is a breaking change to the behavior of this lib, I've published the changes in a new major version `3.0.0`.

**Comment by mrcoles** [comment]
Awesome, thanks!
